<a href="https://colab.research.google.com/github/sitthatkaja/data_viz_2022/blob/main/Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Structure (โครงสร้างข้อมูล)
การเก็บข้อมูลหลายๆตัวไว้ด้วยกันอย่างเป็นระเบียบ


## ```List```
- เก็บอะไรก็ได้
- ลำดับในการเก็บ มีความสำคัญ


In [1]:
list_a = [1,2,3,4,5,6] # [] Square Brackets

In [2]:
list_a

[1, 2, 3, 4, 5, 6]

In [3]:
list_b = ['ab',2,3.14,list_a]

In [4]:
list_b

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]

### Indexing การชี้สมาชิกใน list ด้วยเลขลำดับ list

In [5]:
list_a[3]

4

In [6]:
list_b[3]

[1, 2, 3, 4, 5, 6]

In [7]:
list_b[3][4]

5

In [8]:
list_a[-1] #index -1 คือตัวสุดท้ายของ list

6

In [9]:
list_a[-4]

3

### การสร้าง ```list()```

In [10]:
list_x1 = [] #แบบที่ 1
list_x2 = list() #แบบที่ 2

In [11]:
print(list_x1)
print(list_x2)

[]
[]


### เพิ่มสมาชิกเข้าไปใน list ด้วย ```append()```

In [12]:
list_x1.append(2)

In [13]:
list_x1

[2]

In [14]:
list_x1.append(4)
print(list_x1)

[2, 4]


In [15]:
list_x1[0]

2

In [16]:
list_x1[-1]

4

In [17]:
list_x2

[]

In [18]:
list_x2.append('ha')

In [19]:
list_x2

['ha']

### ลบสมาชิกจาก list

In [20]:
list_x1.append('ha')

In [21]:
list_x1

[2, 4, 'ha']

In [22]:
list_x1.pop()

'ha'

In [23]:
list_x1

[2, 4]

In [24]:
list_x1.pop()
print(list_x1)

[2]


### ```len()``` ตรวจสอบจำนวนสมาชิกของ list

In [25]:
print(list_b)
print(len(list_b))

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]
4


In [26]:
len(list_a)

6

### String is a list of characters

In [27]:
st_stat = 'Department of Statistics, Faculty of Science'

In [28]:
st_stat[10]

' '

In [29]:
len(st_stat)

44

### List Slicing ```:```

```list [จุดเริ่มต้น (ทึบ):จุดสุดท้าย (โปร่ง)]```

```list [จุดเริ่มต้น:จุดสุดท้าย:step]```

In [30]:
list_a

[1, 2, 3, 4, 5, 6]

In [31]:
list_a[2]

3

```:``` Colon

In [32]:
list_a[-3:] # : Colon

[4, 5, 6]

In [33]:
list_a[:4]

[1, 2, 3, 4]

In [34]:
list_a[1:4]

[2, 3, 4]

In [35]:
list_a[:]

[1, 2, 3, 4, 5, 6]

### Step




In [36]:
list_c = [1,2,3,4,5,6,7,8,9,10,11,12,13]

In [37]:
list_c[:10:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [38]:
list_c[:10:2]

[1, 3, 5, 7, 9]

In [39]:
list_c[::-1]

[13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

### ```Range()```

In [40]:
range(21)

range(0, 21)

In [41]:
a = list(range(21))

In [42]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [43]:
list(range(1,21))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

HW2 คำนวณเวลาเป็นวินาทีของเวลาต่อไปนี้โดยใช้คำสั่ง split() ช่วย (print ออกมาอย่างสวยงาม)

- 12:30:15
- 13:41:07
- 09:11:50
- 21:30:15
- 01:10:15

In [44]:
#01:00:00

a=(1*60*60) + (2*+60) + 3
print(f'01:00:00 แปลงเป็นวินาทีได้ {a} วินาที')

01:00:00 แปลงเป็นวินาทีได้ 3723 วินาที


***

In [45]:
q1 = '12:30:15'
q1_sp = q1.split(':')
print(f'ผลการ split ของ {q1} คือ {q1_sp}')
h1 = int(q1_sp[0])*3600
m1 = int(q1_sp[1])*60
s1 = int(q1_sp[2])
aq1 = h1+m1+s1
print(f'แปลงเป็นวินาทิได้เป็น {aq1} วินาที')
print(f'เวลา {q1} คำนวณเป็นจำนวนวินาทีได้เท่ากับ {aq1} วินาที')

ผลการ split ของ 12:30:15 คือ ['12', '30', '15']
แปลงเป็นวินาทิได้เป็น 45015 วินาที
เวลา 12:30:15 คำนวณเป็นจำนวนวินาทีได้เท่ากับ 45015 วินาที


In [46]:
q2 = '13:41:07'
q2_sp = q2.split(':')
print(f'ผลการ split ของ {q2} คือ {q2_sp}')
h2 = int(q2_sp[0])*3600
m2 = int(q2_sp[1])*60
s2 = int(q2_sp[2])
aq2 = h2+m2+s2
print(f'แปลงเป็นวินาทิได้เป็น {aq2} วินาที')
print(f'เวลา {q2} คำนวณเป็นจำนวนวินาทีได้เท่ากับ {aq2} วินาที')

ผลการ split ของ 13:41:07 คือ ['13', '41', '07']
แปลงเป็นวินาทิได้เป็น 49267 วินาที
เวลา 13:41:07 คำนวณเป็นจำนวนวินาทีได้เท่ากับ 49267 วินาที


In [47]:
q3 = '09:11:50'
q3_sp = q3.split(':')
print(f'ผลการ split ของ {q3} คือ {q3_sp}')
h3 = int(q3_sp[0])*3600
m3 = int(q3_sp[1])*60
s3 = int(q3_sp[2])
aq3 = h3+m3+s3
print(f'แปลงเป็นวินาทิได้เป็น {aq3} วินาที')
print(f'เวลา {q3} คำนวณเป็นจำนวนวินาทีได้เท่ากับ {aq3} วินาที')

ผลการ split ของ 09:11:50 คือ ['09', '11', '50']
แปลงเป็นวินาทิได้เป็น 33110 วินาที
เวลา 09:11:50 คำนวณเป็นจำนวนวินาทีได้เท่ากับ 33110 วินาที


In [48]:
q4 = '21:30:15'
q4_sp = q4.split(':')
print(f'ผลการ split ของ {q4} คือ {q4_sp}')
h4 = int(q4_sp[0])*3600
m4 = int(q4_sp[1])*60
s4 = int(q4_sp[2])
aq4 = h4+m4+s4
print(f'แปลงเป็นวินาทิได้เป็น {aq4} วินาที')
print(f'เวลา {q4} คำนวณเป็นจำนวนวินาทีได้เท่ากับ {aq4} วินาที')

ผลการ split ของ 21:30:15 คือ ['21', '30', '15']
แปลงเป็นวินาทิได้เป็น 77415 วินาที
เวลา 21:30:15 คำนวณเป็นจำนวนวินาทีได้เท่ากับ 77415 วินาที


In [49]:
q5 = '01:10:15'
q5_sp = q5.split(':')
print(f'ผลการ split ของ {q5} คือ {q5_sp}')
h5 = int(q5_sp[0])*3600
m5 = int(q5_sp[1])*60
s5 = int(q5_sp[2])
aq5 = h5+m5+s5
print(f'แปลงเป็นวินาทิได้เป็น {aq5} วินาที')
print(f'เวลา {q5} คำนวณเป็นจำนวนวินาทีได้เท่ากับ {aq5} วินาที')

ผลการ split ของ 01:10:15 คือ ['01', '10', '15']
แปลงเป็นวินาทิได้เป็น 4215 วินาที
เวลา 01:10:15 คำนวณเป็นจำนวนวินาทีได้เท่ากับ 4215 วินาที


##Dictionary

- คล้าย list()
- index เป็นอะไรก็ได้ ไม่จำเป็นต้องเป็นตัวเลขลำดับ
- ลำดับไม่มีความสำคัญ 

### สร้าง Dictionary

In [50]:
dict_a = {1:'Happy','N':'New','2022':'Year'} #{} curly brackets

### การชี้ Dictionary

In [51]:
dict_a[1]

'Happy'

In [52]:
dict_a['N']

'New'

In [53]:
dict_a.keys()

dict_keys([1, 'N', '2022'])

### การเพิ่มสมาชิกลงใน Dictionary

In [54]:
dict_a[7] = 3.14

In [55]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'New'}

In [56]:
dict_a['N'] = 'NNNNNEEEEWWW'

In [57]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'NNNNNEEEEWWW'}

##Numpy Array

- เก็บได้แต่ตัวเลข
- อ้างอิงโดยใช้พิกัด (2มิติ ก็มองเป็น Matrix)

In [58]:
import numpy as np

In [59]:
list_A = [1,2,3,4,5]

In [60]:
arr_a = np.array(list_A)

In [61]:
arr_a

array([1, 2, 3, 4, 5])

In [62]:
arr_a[0]

1

In [63]:
list_A[0]

1

In [64]:
5 * arr_a

array([ 5, 10, 15, 20, 25])

In [67]:
5 * list_A

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [68]:
arr_b = np.array([10,20,30,40,50])

In [69]:
print(arr_a)

[1 2 3 4 5]


In [70]:
arr_a + arr_b

array([11, 22, 33, 44, 55])

### 2D array

In [71]:
arr2_z = np.array([[1,2,3],[4,5,6]])

In [72]:
arr2_z

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
arr2_z.shape

(2, 3)

### np.zeros





In [74]:
arr2_3_5_0 = np.zeros((3,5))

In [75]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [76]:
arr2_3_5_0[1,2] = 9

In [77]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [78]:
arr2_3_5_0[1,2]

9.0

In [79]:
print(list_A)
list_A[-1] = 'Christmas'
print(list_A)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 'Christmas']


### np.ones()

In [80]:
arr2_4_5_1 = np.ones((4,5))

In [81]:
arr2_4_5_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [82]:
arr2_4_5_200 = 200*np.ones((4,5))

In [83]:
arr2_4_5_200

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

### Matrix operations

####การบวก ลบ Matrix 

การบวก ลบ Matrix นั้นต้องเท่ากัน

$M \pm N$

In [84]:
arr2_4_5_200 + arr2_4_5_1

array([[201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.]])

#### การคูณ Matrix


- $aM$ scar คูณ Matrix (scalar คูณกระจายเข้าไปทุกตัวของ Matrix)

- $M\times N$ คูณ Matrix (แถว คูณ หลัก)

$aM$

In [85]:
5 * arr_a # (Scalar Multiplication)

array([ 5, 10, 15, 20, 25])

$M\times N$ (dot product)

- (m,n) $\times$ (n,o) = (m,o)(Shape)

In [86]:
mat_a = np.array([[2,3,5],[4,6,7]])
mat_b = np.array([[1,2,5],[2,4,-7]])
mat_c = np.array([[2,3],[4,6],[7,9]])

In [87]:
mat_a

array([[2, 3, 5],
       [4, 6, 7]])

In [88]:
mat_b

array([[ 1,  2,  5],
       [ 2,  4, -7]])

In [89]:
mat_c

array([[2, 3],
       [4, 6],
       [7, 9]])

axc , bxc

In [90]:
np.dot(mat_a,mat_c)

array([[ 51,  69],
       [ 81, 111]])

In [91]:
np.dot(mat_b,mat_c)

array([[ 45,  60],
       [-29, -33]])

cxa cxb

In [92]:
np.dot(mat_c,mat_a)

array([[16, 24, 31],
       [32, 48, 62],
       [50, 75, 98]])

In [93]:
mat_X = np.dot(mat_c,mat_b)
print(mat_X)

[[  8  16 -11]
 [ 16  32 -22]
 [ 25  50 -28]]


In [94]:
mat_a * mat_b #คูณสำแหน่งเดียวกัน

array([[  2,   6,  25],
       [  8,  24, -49]])

### Matrix Slicing

In [95]:
mat_X[:2,:2]

array([[ 8, 16],
       [16, 32]])

HW3

1. สร้าง array ที่เป็นรูปต้น Christmas

2. slice เลข 1 ออกมาจาก array HW3 ด้วยการ slice

In [96]:
HW3 = np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [97]:
HW3[::4,2] = 1
HW3[::4,4] = 1
HW3[::4,6] = 1
HW3[::4,8] = 1
HW3

array([[0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

****

ข้อที่ 1 สร้าง array ที่เป็นรูปต้น Christmas

In [141]:
Xmas = np.ones((11,5))
Xmas[0,2] = 888
Xmas[1,1:4] = 888
Xmas[2,2:3] = 888
Xmas[3:4,1:4] = 888
Xmas[4:5,2:3] = 888
Xmas[5:6,:] = 888
Xmas[6:7,1:4] = 888
Xmas[7:8,:] = 888
Xmas[8:,2] = 525
Xmas

array([[  1.,   1., 888.,   1.,   1.],
       [  1., 888., 888., 888.,   1.],
       [  1.,   1., 888.,   1.,   1.],
       [  1., 888., 888., 888.,   1.],
       [  1.,   1., 888.,   1.,   1.],
       [888., 888., 888., 888., 888.],
       [  1., 888., 888., 888.,   1.],
       [888., 888., 888., 888., 888.],
       [  1.,   1., 525.,   1.,   1.],
       [  1.,   1., 525.,   1.,   1.],
       [  1.,   1., 525.,   1.,   1.]])

ข้อที่ 2 slice เลข 1 ออกมาจาก array HW3 ด้วยการ slice

In [142]:
HW3 = np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [143]:
HW3[::4,2] = 1
HW3[::4,4] = 1
HW3[::4,6] = 1
HW3[::4,8] = 1
HW3

array([[0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [144]:
HW3[::4,2::2]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

##Pandas Dataframe (แยกออกเป็น notebook เฉพาะ)